### ISSUE TITLE
Java Queries not Included in Pypi Package

### ISSUE THREAD

**Issue by ncoop57** [autosoft-dev/tree-hugger#43]
tree-hugger version: 0.10.0

I tried to use the JavaParser:
```
from tree_hugger.core import JavaParser

jp = JavaParser(library_loc="/content/my-languages.so")
```

 However, I ran into this error:
```
QueryFileNotFoundError                    Traceback (most recent call last)
<ipython-input-3-c60a404b4311> in <module>()
      2 from tree_hugger.core import JavaParser
      3 
----> 4 jp = JavaParser(library_loc="/content/my-languages.so")

2 frames
/usr/local/lib/python3.6/dist-packages/tree_hugger/core/queries.py in fromFile(query_file_path)
     21     def fromFile(query_file_path: str):
     22         if not Path(query_file_path).exists() or not Path(query_file_path).is_file():
---> 23             raise QueryFileNotFoundError(f"Cound not find {query_file_path}")
     24 
     25         with open(query_file_path) as f:

QueryFileNotFoundError: Cound not find /usr/local/lib/python3.6/dist-packages/tree_hugger/core/parser/java/queries.yml
```

It seems the somehow the pypi package doesn't include this `queries.yml` file for the java parser. The python one works just fine and when I copy the java `queries.yml` into the location that `tree-hugger` expects, it works as expected. I think there must be some weirdness happening with the pypi packaging that is causing this.

You can reproduce this using this notebook: https://colab.research.google.com/drive/1v7np3pmSIuig-Js1xVP62MbTrc9ru6c2?usp=sharing

BTW love the library! I was actually gonna create something like this, but glad to see now I have a place I can just directly contribute too :D.

**Comment by rcshubhadeep** [comment]
Thank you so much for reporting this bug. I am going to have a look into it :)

**Comment by rcshubhadeep** [comment]
@ncoop57 Thank you again for the bug report. Indeed those .yml files were not shipped with the versions. Now they are. I have updated a new version of tree-hugger in Pypi (0.10.1) 

Please check this colab to see it in action - https://colab.research.google.com/drive/1DUSViETkS_IqG3wfBncWDjr51dgwd05q?usp=sharing

Please let me know if this helps you. 

Sorry for the late reply.

**Comment by ncoop57** [comment]
Awesome, its working great now!
