### ISSUE TITLE
No such attribute error

### ISSUE THREAD

**Issue by madhurimamandal** [autosoft-dev/tree-hugger#44]
When I am trying to use python tree hugger on a file according to [this](https://github.com/autosoft-dev/tree-hugger/blob/master/notebooks/Using_tree_hugger_to_Enhance_CodeXGLUE.ipynb)  example, attributes like "get_all_function_names ", "get_all_function_doctrings " are working, but "get_all_class_methods " and other methods api references are not working. But they are mentioned as available in the Readme. I am getting "No such attribute" error.

```python
import pandas as pd
import numpy as np
from tree_hugger.core import PythonParser

pp = PythonParser(library_loc="/home/xyz/my-languages.so")

pp.parse_file('FeatureV.py')

pp.get_all_class_methods()
```

This is producing the following error: -
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-d1fcd6b98ce4> in <module>
----> 1 pp.get_all_class_methods()

AttributeError: 'PythonParser' object has no attribute 'get_all_class_methods'
```

But some of the attributes are working in the same code, example: -

```python
import pandas as pd
import numpy as np
from tree_hugger.core import PythonParser

pp = PythonParser(library_loc="/home/xyz/my-languages.so")

pp.parse_file('FeatureV.py')

pp.get_all_class_names()
```

Output: -

```
['FeatureView', 'ResetListener', 'ShowSrcListener', 'LinkListener']

```

**Comment by rcshubhadeep** [comment]
Hi @madhurimamandal Thanks for reporting this issue. It was a problem in the documentations. The call should have been `get_all_class_method_names` actually. I have re-checked the doc and I have updated the readme. Please have a look and let me know if you are still facing an issue. 

On a different note, we were planning for sometime to extend tree-hugger to include `pandas` integration and such. And also to normalize the API. Are those something that you may need? Please do not hesitate to let us know.

Thanks again

**Comment by madhurimamandal** [comment]
Yes, it is working for me now. thanks! Pandas integration would really help us a lot.

**Comment by rcshubhadeep** [comment]
You are welcome. Happy that it solved your issue and I am sorry again for the issue with the documentation. We are working on a better doc soon.

We are planning on pandas. Are you presently using tree-hugger for your own project or company / institute project? Just curious.

**Comment by madhurimamandal** [comment]
Yes I am using it for an institute project.

**Comment by rcshubhadeep** [comment]
That's nice to hear

**Comment by rcshubhadeep** [comment]
Can I close this issue now? If you really need pandas integration can you open a new issue so that we can track it there. Thanks
