### ISSUE TITLE
download_libs: 404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by Symbolk** [autosoft-dev/tree-hugger#50]
Thanks for the repo! I came from an issue in py-tree-sitter.

Is this because the service is down?

![image](https://user-images.githubusercontent.com/14107297/142594038-caebb045-dbdd-4387-b83e-de33ffa3b8e6.png)

**Comment by rcshubhadeep** [comment]
Right. We are not anymore able to support s3 based hosting of those libs. But we have created a release - https://github.com/autosoft-dev/tree-hugger/releases/tag/0.10.1 where you can download the required lib by your platform and then can use it.

**Comment by Symbolk** [comment]
Thanks!
