### ISSUE TITLE
Issue: Incompatible for Mac Version

### ISSUE THREAD

**Issue by zunairazaman** [autosoft-dev/tree-hugger#52]
**I get the following error while trying to run for Mac M1 chip: 
# JavaScript
from tree_hugger.core import JavascriptParser
jsp = JavascriptParser(library_loc='py_php_js_cpp_java_darwin_64.so')
jsp.parse_file("index.js")
jsp.get_all_function_names()** 

```
File ~/miniforge3/envs/env_tensor/lib/python3.9/ctypes/__init__.py:374, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    371 self._FuncPtr = _FuncPtr
    373 if handle is None:
--> 374     self._handle = _dlopen(self._name, mode)
    375 else:
    376     self._handle = handle

OSError: dlopen(py_php_js_cpp_java_darwin_64.so, 0x0006): tried: '/Users/zunaira/miniforge3/envs/env_tensor/lib/python3.9/lib-dynload/../../py_php_js_cpp_java_darwin_64.so' (no such file), '/Users/zunaira/miniforge3/envs/env_tensor/bin/../lib/py_php_js_cpp_java_darwin_64.so' (no such file), 'py_php_js_cpp_java_darwin_64.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))), '/usr/local/lib/py_php_js_cpp_java_darwin_64.so' (no such file), '/usr/lib/py_php_js_cpp_java_darwin_64.so' (no such file), '/Users/zunaira/Desktop/JScode2vec/CodeSummarizer/py_php_js_cpp_java_darwin_64.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)
```

**Comment by zunairazaman** [comment]
@rcshubhadeep Can you please help me why Mac Update - 19.11.2021 - is still not working for me.

We are not able to support the s3 based download anymore. So the download_libs command does not work. We are making them available via this release - https://github.com/autosoft-dev/tree-hugger/releases/tag/0.10.1 Please download the required zip file from there :(

**Comment by rcshubhadeep** [comment]
Hi,

Thanks for letting us know. I am suspecting that you are using M1/M2 Mac (as you said) the processor architecture is different. The libraries that are available here were compiled on a intel 64 bit architecture. Hence they won't work on a M1/M2 Mac. 

I am sorry that it did not work for you. I do not have access to a M1 mac and hence I can't compile them myself. But you may be able to compile the new libraries. You can do two things. 

1. Try the `create_libs` command. It is already shipped with tree-hugger. You can run `create_libs --help` to know about the options. This may solve your problem. 
2. If this does not solve your problem then go have a look at [here](https://github.com/autosoft-dev/tree-hugger/blob/master/tree_hugger/cli/create_libs.py). You will be able to see what the command does under the hood. It is very simple actually. And you can perform those steps separately to check if that makes a successful build. 

Hope this helps. I am presently not in a situation to actually support the development of tree_hugger. So sorry if this does not help. 

Also one small request, if you do compile the libraries please consider opening a PR here to add them to tree-hugger to help people like yourself in the future. 

All the best.

**Comment by zunairazaman** [comment]
Thanks, It worked. Another query is how can we parse the Javascript all class method bodies. Currently, it can parse JS functions but not JS class method bodies. Thanks!

**Comment by rcshubhadeep** [comment]
I am happy that it helped you. The method bodies are not implemented yet, but you can easily extend tree_hugger to do that. Please have a look into the three following resources to have an idea how that can be done

1.> How to extend tree_hugger - https://github.com/autosoft-dev/tree-hugger#extending-tree-hugger

2.> The method that gives you `method names` from JS classes - https://github.com/autosoft-dev/tree-hugger/blob/master/tree_hugger/core/parser/javascript/javascript_parser.py#L29

3.> The query that eanbles it to do so - https://github.com/autosoft-dev/tree-hugger/blob/master/tree_hugger/core/parser/javascript/queries.yml#L16

I am guessing using these resources you can come up with a custom parser class that can achieve what you want to do. I will be happy to answer any further question. 

If you do not mind me asking what kind of work are you using tree_hugger for?
